In [1]:
import torch

In [2]:
A = torch.arange(24).reshape(2,3,4)
C = A.sum(dim=0,keepdims=True)
A, C, C.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[12, 14, 16, 18],
          [20, 22, 24, 26],
          [28, 30, 32, 34]]]),
 torch.Size([1, 3, 4]))

In [3]:
a = torch.ones((2,5,4))
a.shape

torch.Size([2, 5, 4])

In [4]:
b = a.sum(dim=[0,2], keepdims=True)
b, b.shape

(tensor([[[8.],
          [8.],
          [8.],
          [8.],
          [8.]]]),
 torch.Size([1, 5, 1]))

In [7]:
A = torch.ones(2,1)
A, A.T

(tensor([[1.],
         [1.]]),
 tensor([[1., 1.]]))

In [8]:
X = torch.arange(24).reshape(2,3,4)
Y = X.sum(dim=[0])
Y, Y.T

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 20, 28],
         [14, 22, 30],
         [16, 24, 32],
         [18, 26, 34]]))

In [9]:
x = torch.arange(4,dtype=torch.float32, requires_grad=True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [10]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [11]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [14]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [15]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [18]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])